// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "health check",
                "operationId": "1",
                "responses": {
                    "200": {
                        "description": "health check response with, db connection, sqlite version,and app version ",
                        "schema": {
                            "$ref": "#/definitions/HealthCheck"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create a new system user",
                "operationId": "create-user",
                "parameters": [
                    {
                        "description": "payload to ceate new app user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AppNewUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": " To create new user",
                        "schema": {
                            "$ref": "#/definitions/AppNewUser"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AppNewUser": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "dateCreated": {
                    "type": "string"
                },
                "dateUpdated": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "HealthCheck": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "integer"
                },
                "db_version": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "maxProcess": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
