definitions:
  AppUser:
    properties:
      dateCreated:
        type: string
      dateUpdated:
        type: string
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/AppUser'
      summary: Greeter service
  /healthdv:
    get:
      operationId: "2"
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: test service
swagger: "2.0"
