definitions:
  AppNewUser:
    properties:
      dateCreated:
        type: string
      dateUpdated:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  HealthCheck:
    properties:
      database:
        type: integer
      db_version:
        type: string
      host:
        type: string
      maxProcess:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: 'health check response with, db connection, sqlite version,and
            app version '
          schema:
            $ref: '#/definitions/HealthCheck'
      summary: health check
  /users:
    post:
      operationId: create-user
      parameters:
      - description: payload to ceate new app user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/AppNewUser'
      produces:
      - application/json
      responses:
        "200":
          description: ' To create new user'
          schema:
            $ref: '#/definitions/AppNewUser'
      summary: create a new system user
swagger: "2.0"
