info:
  contact: {}
paths:
  /health:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Greeter service
  /healthdv:
    get:
      operationId: "2"
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: test service
swagger: "2.0"
